language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: jNfobuwPAszOKjyd4sRnaR0jj6MiJuM7KwmeNmDwHg6vDRsPjws/u2SbnSRTnaSp12B6PxDLXyxXdQmIwgV4e2Mr7cKQofXSXrVCwlMqeSwN2mVAJfTFkuca6NFakNXmGSqyu3UODVaWtEY6ERYYBKy10wuVpN5ZfdEhQz2LbsMWBTs+tf7VRwgqYMlkNqwsporrKt5BMChxG9jrefyKtE0W14RCw81U/LZrSXosQLGNRrqjuYBX0nYsOFNhHeJKpDHkdWNl0nGZRLpBtVJIDO8PNXAI8ig7ECbKk/TYbzdOfO8vwd1UqNsKmVp7sFYVwv3BL+DRg3RYdhDcL7obaIExjcEfdCf95uhvftYgd09J0LG9BmQbzrlaTshYoumW63ZN1TcsepLCkAgKJP2/MgSMQI33kBN4BOxV/4D9BRi6+Q/vt7SC1Bcj59EybsYsXfEQIp5tE0o9+CAxt8MJCyZp8zvL4N5lL46S1w3fqWfRpHPC4UP5+B1mW090IO88h942QG3dfaC+GOUiMl3T4/jVWduSdSB1yglI62VhsVdWQdel+6sm5zaWbDNuKVgYst8irn/EY3LgnXUSfHAke2+NpHpI68RJOnjvfkshQ24DuvplaYmnJwX41A8Qd1AX4ydU6qUOmil9QIRaQgbs7ssO67WPESciZfzTTMjYDvo=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
